databases:
  - name: fertility-db
    databaseName: fertility_database
    plan: free
    ipAllowList: [] #only allow connections from the app

services:
  - type: web
    name: fertility-backend
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    plan: free
    rootDir: .
    branch: main
    envVars:
      - key: COHERE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.13.4"
      - key: DATABASE_URL
        fromDatabase:
          name: fertility-db
          property: connectionString

